version: '2.3'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /usr/app/
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links: 
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - /data/db
    ports:
      - 27017:27017
